# Production Docker Compose (Optional - mainly for AWS deployment)
# For Vercel deployment, use the deployment scripts instead

version: '3.8'

services:
  # Main Host Application - Production
  main-host:
    build:
      context: ../..
      dockerfile: tools/dockerconfig/Dockerfile
      args:
        APP_NAME: zionix-main-host
      target: production
    container_name: zionix-main-host-prod
    ports:
      - "4200:3000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - zionix-prod-network

  # Admin App - Production
  admin-app:
    build:
      context: ../..
      dockerfile: tools/dockerconfig/Dockerfile
      args:
        APP_NAME: adminApp
      target: production
    container_name: zionix-admin-app-prod
    ports:
      - "4201:3000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - zionix-prod-network

networks:
  zionix-prod-network:
    driver: bridge